<a href="https://colab.research.google.com/github/hydrationn/AI-based-Representation-and-Problem-Solving/blob/main/20240313_2%EC%A3%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3],dtype = np.uint8)
print(arr)
print(type(arr))
print(type(arr[0]))
print(arr.shape)

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.uint8'>
(3,)


In [ ]:
arr1 = np.arange(0,10,2)
arr2 = np.linspace(0,10,5)
arr3  = np.linspace(0,10,5, endpoint=False)
print(arr1)
print(arr2)
print(arr3)

[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[0. 2. 4. 6. 8.]


In [ ]:
arr4 = np.ones((4,4))
print(arr4)
print(arr4[0:3, 2:4])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arr5 = np.full((2,2),3)
eye1 = np.eye(3,2,dtype = np.uint8)
eye2 = np.eye(2)

print(arr5)
print(eye1)
print(eye2)

[[3 3]
 [3 3]]
[[1 0]
 [0 1]
 [0 0]]
[[1. 0.]
 [0. 1.]]


In [ ]:
arr3 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [11,12,13,14]])
print(arr3[0:3,2:4])

[[ 3  4]
 [ 7  8]
 [11 12]]


In [ ]:
A = np.array([[1,2],[3,4]],dtype=np.uint8)
B = np.eye(2)
C = np.multiply(A,B)
D = np.dot(A,B)

print(A)
print(B)
print(C)
print(D)

[[1 2]
 [3 4]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 4.]]
[[1. 2.]
 [3. 4.]]


In [ ]:
class Hello:
  def __init__(self):
    self.morn = "Good Morning!"
  def morning(self):
    print(self.morn)

a = Hello()
a.morning()

Good Morning!


In [ ]:
class Person():
  def __init__(self, name, sex, age):
    self.name = name
    self.sex = sex
    self.age = age

  def introduce(self):
    print('이름: %s' %self.name)
    print('성별: %s' %self.sex)
    print('나이: %d' %self.age)

p = Person("박수화", "여성", 23)
p.introduce()

이름: 박수화
성별: 여성
나이: 23


In [ ]:
import torch
x = torch.empty(4,2)
print(x)

tensor([[-1.8917e-38,  4.4002e-41],
        [-1.8917e-38,  4.4002e-41],
        [ 2.5353e+30,  3.6434e-44],
        [ 3.3491e-43,  1.9890e-41]])


In [ ]:
x = torch.rand(4,2)
print(x)

tensor([[0.8461, 0.4726],
        [0.4084, 0.4263],
        [0.1875, 0.5315],
        [0.6502, 0.2014]])


In [ ]:
x = torch.zeros(4,2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [ ]:
x = torch.tensor([3,2,3])
print(x)

tensor([3, 2, 3])


In [ ]:
x = x.new_ones(2,4,dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [ ]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.0134, -0.0863,  0.3708,  1.3377],
        [ 0.2517,  0.8439,  0.0601, -0.1894]])


In [ ]:
print(x.size())

torch.Size([2, 4])


In [ ]:
# 중요
# 4D Tensor: 샘플, 높이, 너비, 채널